on: [push]

jobs:
  deploy_job:
    runs-on: self-hosted
    name: build&deploy
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: make directory and create file
        run: touch aramtestFileforDeployment.txt
      - name: Install Dependencies
        run: npm build

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          
#      - name: Deploy
#        run: |
 #         TEMP=$(mktemp)
  #        echo "${{ secrets.SSH_KEY }}" > $TEMP
   #       ssh -o 'StrictHostKeyChecking no' -i $TEMP aram@143.198.131.117
    #      cd /home/aram/aram-react/myreact
     #     git reset --hard
      #    git pull origin  main
       #   npm install
        #  npm run build

      - name: Deploy
        run: |
          TEMP=$(mktemp)
          echo "${{ secrets.SSH_KEY }}" > $TEMP
          ssh -o 'StrictHostKeyChecking no' -i $TEMP  aram@143.198.131.117 "cd /home/aram/aram-react;git reset --hard;git pull origin  main;"


#      - name: Deploy to server
 #       uses: fifsky/ssh-action@master
  #      with:
   #       host: ${{ secrets.SSH_HOST }}
    #      user: ${{ secrets.SSH_USERNAME }}
     #     key: ${{ secrets.SSH_KEY}}
      #    command: |
 #           cd /var/www/aram-react/myreact
  #          sudo git reset --hard
   #         sudo git pull origin  main
    #        sudo npm install
     #       sudo npm run build
