on: [push]

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: build&deploy
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2


      - name: install Dependencies
        run: npm install 
        
      - name: build Dependencies
        run: npm build

      - name: deploy file to server
        uses: appleboy/ssh-action@main
        with:
          SSH_USERNAME: '${{ secrets.SSH_USERNAME }}'
          SSH_HOST: '${{ secrets.SSH_HOST }}'
          SSH_KEY: '${{ secrets.SSH_KEY }}'
          local_path: './build/*'
          remote_path: '/home/aram/aram-react/myreact'
          args: '-o ConnectTimeout=5'
          
