on: [push]

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: build&deploy
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2


      - name: install Dependencies
        run: npm install 
        
      - name: build Dependencies
        run: npm build

      - name: deploy file to server
        uses: appleboy/ssh-action@v0.1.2
        with:
          username: '${{ secrets.SSH_USERNAME }}'
          host: '${{ secrets.SSH_HOST }}'
          key: '${{ secrets.SSH_KEY }}'
          local_path: './build/*'
          remote_path: '/home/aram/aram-react/myreact'
          args: '-o ConnectTimeout=5'
          
